version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    restart: always
    env_file:
      - .env

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini

    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_DB_PREFIX}
    links:
      - mysql
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_LOGS}:/var/log/nginx/
    ports:
      - 8080:80
    links:
      - wordpress
    env_file:
      - .env