version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - ${MYSQL_PATH:?err}/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:?err}
      MYSQL_USER: ${WORDPRESS_DB_USER:?err}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:?err}
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ${WORDPRESS_LOCAL_HOME:?err}/:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG:?err}/:/usr/local/etc/php/conf.d/uploads.ini

    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:?err}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:?err}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:?err}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_DB_PREFIX:?err}
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ${NGINX_CONF:?err}:/etc/nginx/conf.d/default.conf
      - ${WORDPRESS_LOCAL_HOME:?err}/:/var/www/html
      - ${NGINX_LOGS:?err}/:/var/log/nginx/
      - ${LETSENCRYPT1:?err}:${LETSENCRYPT1:?err}
      - ${LETSENCRYPT2:?err}:${LETSENCRYPT2:?err}

    ports:
      - ${NGINX_PORT_443:?err}:443
    links:
      - wordpress
