version: '3'
services:
  mariadb:
    image: mariadb
    volumes:
      - ${PATH_VOLUME:?err}/${PROJECT_FOLDER:?err}/mariadb/:/var/lib/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:?err}
      MYSQL_USER: ${WORDPRESS_DB_USER:?err}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:?err}
    restart: always

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - ${PATH_VOLUME:?err}/${PROJECT_FOLDER:?err}/wordpress/:/var/www/html
      - ${PATH_YML:?err}/${PROJECT_FOLDER:?err}/uploads.ini/:/usr/local/etc/php/conf.d/uploads.ini

    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:?err}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:?err}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:?err}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_DB_PREFIX:?err}
    links:
      - mariadb
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ${PATH_YML:?err}/${PROJECT_FOLDER:?err}/default.conf:/etc/nginx/conf.d/default.conf
      - ${PATH_VOLUME:?err}/${PROJECT_FOLDER:?err}/wordpress/:/var/www/html
      - ${PATH_VOLUME:?err}/${PROJECT_FOLDER:?err}/logs/:/var/log/nginx/
      - /etc/letsencrypt/live/${DOMAIN:?err}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN:?err}/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN:?err}/privkey.pem:/etc/letsencrypt/live/${DOMAIN:?err}/privkey.pem

    ports:
      - ${NGINX_PORT_443:?err}:443
    links:
      - wordpress
